site_name: anHALytics Documentation
repo_url: https://github.com/anHALytics/anHALytics-documentation
repo_name: GitHub
theme: readthedocs
site_description: Documentation for anHALytics
docs_dir: .
include_search: true
pages:
- ['index.md', 'Home']
- ['Introduction.md', 'About', 'Introduction']
- ['References.md', 'About', 'References']
- ['License.md', 'About', 'License']
- ['Install-backend.md', 'User manual', 'Install anHALytics backend']
- ['Install-frontend.md', 'User manual', 'Install anHALytics frontend']
- ['Annotations.md', 'Developer notes', 'Description of the annotations/extractions']
- ['Data-models.md', 'Developer notes', 'Data models']
- ['Workflows.md', 'Developer notes', 'Component workflows']
- ['Running.md', 'Developer notes', 'Running anALytics at Inria']

