site_name: anHALytics Documentation
repo_url: https://github.com/anHALytics/anHALytics-documentation
repo_name: GitHub
site_description: Documentation for anHALytics
docs_dir: doc/
plugins:
    - search
theme:
    name: readthedocs
pages:
  - Home: 'index.md'
  - About:
    - Introduction: 'Introduction.md'
    - References: 'References.md'
    - License: 'License.md'
  - User manual:
    - Install anHALytics backend: 'Install-backend.md'
    - Install anHALytics frontend: 'Install-frontend.md'
  - Developer notes:
      - Description of the annotations/extractions: 'Annotations.md'
      - Data models: 'Data-models.md'
      - Component workflows: 'Workflows.md'
      - Running anHALytics at Inria: 'Running.md'
